// src/components/PageHeader.tsx
import { Link } from "@void/react";
import CloudflareSignIn from "@/components/CloudflareSignIn";
import Dropdown from "@/components/Dropdown";
import { SITE } from "@/lib/env";

export interface PageHeaderProps { compact?: boolean }

// The search box sits in the centre section on the SvelteKit site; it is indexed from the docs, which have not been
// migrated yet, so the section stays empty until they are (see docs/migration.md).
export default function PageHeader({ compact = false }: PageHeaderProps) {
  return (
    <header className="page-header">
      <div className="wrapper wrapper-lg">
        <div className="header-section left">
          <Link href="/" className={`logo${compact ? " logo-sm" : ""}`} title={`voidbase ${SITE.vbVersion}${SITE.pbVersion ? ` · PocketBase ${SITE.pbVersion} API` : ""}`}>
            <img src="/images/logo.svg" alt="voidbase logo" width="40" height="40" />
            <span className="txt">void<strong>base</strong></span>
            <span className="version">{SITE.vbVersion}</span>
          </Link>
        </div>

        <div className="header-section center" />

        <div className="header-section right">
          <Dropdown
            className="dropdown dropdown-lg dropdown-right dropdown-nowrap responsive-menu-dropdown"
            trigger={({ active, onClick, "aria-expanded": expanded }) => (
              <button type="button" className={`btn btn-circle btn-secondary responsive-menu-btn${active ? " active" : ""}`} title="Menu" aria-expanded={expanded} onClick={onClick}>
                <span />
                <i className="ri-menu-3-fill" />
              </button>
            )}
          >
            <Link href="/docs" className="dropdown-item">Docs</Link>
            <Link href="why" className="dropdown-item">Why</Link>
            <Link href="/cloud" className="dropdown-item">Cloud</Link>
            <a href={SITE.discussionsUrl} className="dropdown-item" target="_blank" rel="noreferrer noopener">Discussions</a>
            <hr />
            <CloudflareSignIn className="dropdown-item" />
          </Dropdown>

          <nav className="main-menu">
            <Link href="/docs" className="btn btn-secondary">Docs</Link>
            <Link href="/docs/why" className="btn btn-secondary">Why</Link>
            <a href={SITE.repoUrl} className="btn btn-circle btn-secondary" target="_blank" rel="noreferrer noopener" title="GitHub Repo">
              <i className="ri-github-line" />
            </a>
            <CloudflareSignIn className="btn btn-secondary cf-header" />
          </nav>
        </div>
      </div>
    </header>
  );
}

// src/lib/components/PageHeader.svelte
<script>
    import Toggler from "@/components/Toggler.svelte";
    import Searchbar from "@/components/Searchbar.svelte";

    export let compact = false;
</script>

<header class="page-header">
    <div class="wrapper wrapper-lg">
        <div class="header-section left">
            <a
                href="/"
                class="logo"
                class:logo-sm={compact}
                data-sveltekit-preload-data
                title="voidbase {import.meta.env.PB_VB_VERSION} · PocketBase {import.meta.env.PB_VERSION} API"
            >
                <img src="/images/logo.svg" alt="voidbase logo" width="40" height="40" />
                <span class="txt">void<strong>base</strong></span>
                <span class="version">{import.meta.env.PB_VB_VERSION}</span>
            </a>
        </div>

        <div class="header-section center">
            <Searchbar />
        </div>

        <div class="header-section right">
            <button type="button" class="btn btn-circle btn-secondary responsive-menu-btn" title="Menu">
                <span />
                <i class="ri-menu-3-fill" />
                <Toggler class="dropdown dropdown-lg dropdown-right dropdown-nowrap responsive-menu-dropdown">
                    <a href="/faq" class="dropdown-item" data-sveltekit-preload-data>FAQ</a>
                    <a href="/cloud" class="dropdown-item" data-sveltekit-preload-data>Cloud</a>
                    <a
                        href={import.meta.env.PB_DISCUSSIONS_URL}
                        class="dropdown-item"
                        target="_blank"
                        rel="noreferrer noopener"
                    >
                        Discussions
                    </a>
                    <hr />
                    <a href="/docs" class="dropdown-item" data-sveltekit-preload-data>
                        <span class="txt">Documentation</span>
                    </a>
                </Toggler>
            </button>

            <nav class="main-menu">
                <a href="/faq" class="btn btn-secondary" data-sveltekit-preload-data>FAQ</a>
                <a href="/cloud" class="btn btn-secondary" data-sveltekit-preload-data>Cloud</a>
                <a
                    href={import.meta.env.PB_REPO_URL}
                    class="btn btn-circle btn-secondary"
                    target="_blank"
                    rel="noreferrer noopener"
                    title="GitHub Repo"
                >
                    <i class="ri-github-line" />
                </a>
                <a href="/docs" class="btn btn-outline" data-sveltekit-preload-data>
                    <span class="txt">Documentation</span>
                </a>
            </nav>
        </div>
    </div>
</header>
